name: Lint
on:
  pull_request:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with: # Needed for commitlint
        fetch-depth: 0

    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-rubocop-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-rubocop-

    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle config set without 'default'
        bundle install --jobs 4 --retry 3

    - name: Run RuboCop
      run: bundle exec rubocop --parallel --require rubocop/formatter/checkstyle_formatter --format RuboCop::Formatter::CheckstyleFormatter --out /tmp/checkstyle.xml

    - name: Lint commit messages 
      uses: wagoid/commitlint-github-action@v2

    - name: Lint Markdown
      uses: avto-dev/markdown-lint@v1.5.0

    - uses: check-run-reporter/action@v2.0.0
      if: ${{ always() }}
      with:
        token: '2005ace6-d376-42b7-ac05-1d3b8e8e9d24'
        report: '/tmp/checkstyle.xml'
